/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SM3Util */

#ifndef _Included_SM3Util
#define _Included_SM3Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SM3Util
 * Method:    sm3
 * Signature: ([BI[B)V
 */
JNIEXPORT void JNICALL Java_SM3Util_sm3
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
